### ISSUE TITLE
Cannot make requests from chrome extension due to access control headers

### ISSUE THREAD

**Issue by edcous** [codeths/eths-dashboard#1]
```Access to fetch at 'http://localhost:3000/api/v1/ext/register' from origin 'chrome-extension://gdfdnabnfpcglmejhcealepehpfnghoi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

Obviously, no-cors doesn't work, as that would prevent us from seeing the response body. These headers will need to be set server side.

**Comment by mswider** [comment]
@edcous Has this been resolved by [feat(ext): add CORS headers to controller](https://github.com/codeths/eths-dashboard/commit/f7c91afc16baa0c1037af314c3a8b895e94951b8)?
If so, could I close the issue & pr?
